version: "3.8"

services:
  app:
    user: "${USER_ID}"
    hostname: "${HOST_NAME}"
    image: cybulde-data-preparation
    platform: linux/amd64
    container_name: cybulde-data-preparation-container
    build:
      context: .
      dockerfile: ./docker/Dockerfile
      args:
        USER_NAME: "${USER_NAME}"
        USER_ID: "${USER_ID}"
    volumes:
      - ./:/app/
      - ~/.config/gcloud/:/home/${USER_NAME}/.config/gcloud
    ports:
      - 8888:8888
      
    ipc: host
    init: true


